### ISSUE TITLE
Compilation errors on debian 10.7

### ISSUE THREAD

**Issue by bounmed** [RubixML/Tensor#23]
I got three errors when trying to install the tensor package using pecl.
Error 1:
`/tmp/pear/temp/tensor/ext/tensor.c:25:10: fatal error: cblas.h: No such file or directory`
Error 2:
`/tmp/pear/temp/tensor/ext/include/linear_algebra.c:7:10: fatal error: lapacke.h: No such file or directory`
Error 3:
```
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
```
The solution is to install libopenblas,  libraries and gfortran.
```
apt-get install libopenblas-dev
apt-get install liblapacke-dev
apt-get install gfortran
```

**Comment by andrewdalpino** [comment]
Thanks @bounmed but we've already listed the compilation instructions on the README!

**Comment by stillartem** [comment]
@bounmed thank you, your solution have helped me
