### ISSUE TITLE
Is there any TS windows build?

### ISSUE THREAD

**Issue by takielias** [RubixML/Tensor#30]
Is there any TS (Thread Safe) windows build?

**Comment by DrDub** [comment]
I see you have been in touch with @federicoemartinez in #22. Adding the link here for reference to others.

**Comment by federicoemartinez** [comment]
I haven't been able to build it with TS, I don't use TS in general. But another user posted that you can download it from
https://github.com/jb-lopez/php-extensions-windows/releases/tag/Tensor
