### ISSUE TITLE
SVD not implemented in polyfill

### ISSUE THREAD

**Issue by ahmaruff** [RubixML/Tensor#37]
I tried use this library with laravel,
there is no issue when installation via composer `composer require rubix/tensor`.
but when I try call TruncatedSVD() (which is require this lib)
it show error "The tensor extension is not installed, check PHP configuration"

my machine is
Windows 10
PHP 8.1.7 x64 (laragon)

I haven't tried using pear/pecl because I have problem in installation that tool.

**Comment by andrewdalpino** [comment]
Ah yeah, we didn't implement SVD in the polyfill because we just don't have the resources currently. It's a pretty complicated algorithm. With the extension, we call LAPACK under the hood. There's no such equivalent in PHP land currently.

**Comment by ahmaruff** [comment]
Thanks for the explanation. It'a clear now. I'll close this issue
